
export const TOP_150_SOCIAL = [
  'github.com', 'twitter.com', 'instagram.com', 'reddit.com', 'facebook.com', 'tiktok.com', 'pinterest.com', 
  'tumblr.com', 'snapchat.com', 'mastodon.social', 'vk.com', 'ok.ru', 'weibo.com', 'zhihu.com', 
  'tieba.baidu.com', 'mewe.com', 'gab.com', 'gettr.com', 'truthsocial.com', 'bere.al', 'lemon8-app.com', 
  'threads.net', 'bsky.app', 'cohost.org', 'post.news', 't2.social', 'hive.social', 'counter.social', 
  'parler.com', 'rumble.com', 'odysee.com', 'bitchute.com', 'dailymotion.com', 'bandcamp.com', 
  'mixcloud.com', 'discogs.com', 'rateyourmusic.com', '500px.com', 'unsplash.com', 'pexels.com', 
  'pixabay.com', 'shutterstock.com', 'myportfolio.com', 'canva.com', 'figma.com', 'sketch.com', 
  'invisionapp.com', 'zeplin.io', 'abstract.com', 'framer.com', 'webflow.com', 'linkedin.com', 
  'quora.com', 'flickr.com', 'vimeo.com', 'soundcloud.com', 'behance.net', 'dribbble.com', 'medium.com', 
  'deviantart.com', 'goodreads.com', 'last.fm', 'letterboxd.com', 'strava.com', 'komoot.com', 
  'alltrails.com', 'fitbit.com', 'myfitnesspal.com', 'duolingo.com', 'codecademy.com', 'freecodecamp.org', 
  'khanacademy.org', 'coursera.org', 'udemy.com', 'edx.org', 'skillshare.com', 'aminoapps.com', 
  'band.us', 'newsclapper.com', 'couchsurfing.com', 'eyeem.com', 'foursquare.com', 'glassdoor.com', 
  'influenster.com', 'italki.com', 'kickstarter.com', 'myspace.com', 'nextdoor.com', 'periscope.tv', 
  'reverbnation.com', 'scribd.com', 'slideshare.net', 'wattpad.com', 'weheartit.com', 'yelp.com', 
  'taringa.net', 'skyrock.com', 'hi5.com', 'tagged.com', 'netlog.com', 'bebo.com', 'joindiaspora.com', 
  'friendi.ca', 'pixelfed.org', 'ello.co', 'meetic.com', 'twoo.com', 'untappd.com', 'wayn.com', 
  'interpals.net', 'zapera.com', 'xing.com', 'viadeo.com', 'care2.com', 'habbo.com', 'gaiaonline.com', 
  'imvu.com', 'secondlife.com', 'avakin.com', 'moviestarplanet.com', 'clubcoee.com', 'ourworld.com', 
  'vampirefreaks.com', 'gothpassions.com', 'mubi.com', 'trakt.tv', 'tvtime.com', 'myanimelist.net', 
  'anime-planet.com', 'vgmdb.net', 'kooapp.com', 'bitclout.com', 'minds.com', 'beeper.com', 
  'pawoo.net', 'baraag.net', 'misskey.io', 'calckey.social', 'pleroma.social', 'friendica.me', 
  'pixelfed.social', 'infosec.exchange', 'hachyderm.io', 'techhub.social', 'fosstodon.org', 
  'chaos.social', 'kolektiva.social', 'climatejustice.social', 'sunny.garden'
];

export const TOP_150_NSFW = [
  'onlyfans.com', 'fansly.com', 'pornhub.com', 'xvideos.com', 'xnxx.com', 'xhamster.com', 'chaturbate.com', 
  'cam4.com', 'bongacams.com', 'stripchat.com', 'livejasmin.com', 'manyvids.com', 'clips4sale.com', 
  'iwantclips.com', 'loyalfans.com', 'pocketstars.com', 'fapello.com', 'thothub.to', 'coomer.party', 
  'kemono.party', 'simpcity.su', 'vipergirls.to', 'planetsuzy.org', 'adultwork.com', 'escort-directory.com', 
  'eurogirlsescort.com', 'slixa.com', 'eros.com', 'yesbackpage.com', 'bedpage.com', 'cityxguide.com', 
  'rubratings.com', 'massageanywhere.com', 'listcrawler.com', 'skipthegames.com', 'megapersons.com', 
  'locanto.com', 'doublelist.com', 'squirt.org', 'adam4adam.com', 'fetlife.com', 'recon.com', 'kink.com', 
  'modelmayhem.com', 'purpleport.com', 'starnow.com', 'castingcall.club', 'backstage.com', 'redtube.com', 
  'youporn.com', 'tube8.com', 'spankbang.com', 'eporner.com', 'tnaflix.com', 'motherless.com', 
  'heavy-r.com', 'efukt.com', 'documentingreality.com', 'theync.com', 'kaotic.com', 'goregrish.com', 
  'crazyshit.com', 'rule34.xxx', 'gelbooru.com', 'danbooru.donmai.us', 'e621.net', 'furaffinity.net', 
  'inkbunny.net', 'pixiv.net', 'hentai-foundry.com', 'nhentai.net', 'hitomi.la', 'tsumino.com', 
  'pururin.to', 'e-hentai.org', 'hanime.tv', 'hentaihaven.xxx', 'multporn.net', '8muses.com', 
  'doujins.com', 'luscious.net', 'hbrowse.com', 'simply-hentai.com', 'fakku.net', 'hentai2read.com', 
  'hentaihere.com', 'mama-hentai.com', 'readhentai.com', 'asmhentai.com', 'hentaivideoworld.com', 
  'tmohentai.com', 'verhentai.com', 'hentaisage.com', 'hentai-pulse.com', 'hentai-img.com', 
  'hentai-cosplays.com', 'hentai-moon.com', 'hentai-pros.com', 'hentai-galaxy.com', 'hentai-fox.com', 
  'hentai-cafe.com', 'hentai-lib.com', 'hentai-era.com', 'hentai-zone.com', 'hentai-network.com', 
  'hentai-paradise.com', 'hentai-stream.com', 'hentai-world.com', 'hentai-hub.com', 'hentai-room.com', 
  'hentai-garden.com', 'hentai-house.com', 'hentai-manga.com', 'hentai-comic.com', 'hentai-art.com', 
  'hentai-image.com', 'hentai-picture.com', 'hentai-gallery.com', 'hentai-collection.com', 
  'hentai-archive.com', 'hentai-vault.com', 'hentai-nexus.com', 'hhv2.com', 'hentai-cloud.com', 
  'hentai-storage.com', 'hentai-box.com', 'hentai-drive.com', 'hc2.com', 'hentai-master.com', 
  'hentai-lord.com', 'hentai-king.com', 'hentai-queen.com', 'hentai-prince.com', 'hentai-princess.com', 
  'hentai-knight.com', 'hentai-slayer.com', 'hentai-hunter.com', 'adultfriendfinder.com', 'ashleymadison.com', 
  'seeking.com', 'sugarbook.com', 'secretbenefits.com', 'whatsyourprice.com'
];

export const TOP_200_LIVE_VIDEO_GAMING = [
  'twitch.tv', 'youtube.com', 'kick.com', 'trovo.live', 'dlive.tv', 'tiktok.com', 'instagram.com', 
  'facebook.com', 'vimeo.com', 'dailymotion.com', 'bilibili.com', 'nicovideo.jp', 'douyu.com', 
  'huya.com', 'afreecatv.com', 'steamcommunity.com', 'roblox.com', 'minecraft.net', 'namemc.com', 
  'epicgames.com', 'battle.net', 'origin.com', 'uplay.com', 'gog.com', 'itch.io', 'gamejolt.com', 
  'nexusmods.com', 'curseforge.com', 'speedrun.com', 'tracker.gg', 'op.gg', 'faceit.com', 'play.esea.net', 
  'challengermode.com', 'battlefy.com', 'smash.gg', 'liquipedia.net', 'anilist.co', 'kitsu.io', 'u.gg', 
  'mobafire.com', 'dotabuff.com', 'hltv.org', 'overbuff.com', 'tracker.network', 'sc2replaystats.com', 
  'warcraftlogs.com', 'fflogs.com', 'raider.io', 'wowprogress.com', 'mmo-champion.com', 'wowhead.com', 
  'hearthpwn.com', 'icy-veins.com', 'mtggoldfish.com', 'hearthstonetopdecks.com', 'tappedout.net', 
  'deckstats.net', 'moxfield.com', 'cardmarket.com', 'tcgplayer.com', 'poptropica.com', 'neopets.com', 
  'webkinz.com', 'animaljam.com', 'starstable.com', 'howrse.com', 'flightrising.com', 'dragonadopters.com', 
  'chickenonaraft.com', 'kongregate.com', 'armorgames.com', 'newgrounds.com', 'miniclip.com', 'pogo.com', 
  'addictinggames.com', 'crazygames.com', 'y8.com', 'kizi.com', 'friv.com', 'coolmathgames.com', 
  'chess.com', 'lichess.org', 'playok.com', 'boardgamearena.com', 'tabletopia.com', 'vassalengine.org', 
  'roll20.net', 'foundryvtt.com', 'dndbeyond.com', 'worldanvil.com', 'obsidianportal.com', 
  'myth-weavers.com', 'rpg.stackexchange.com', 'giantitp.com', 'enworld.org', 'rpg.net', 'rpggeek.com', 
  'boardgamegeek.com', 'videogamegeek.com', 'gamefaqs.gamespot.com', 'gamespot.com', 'ign.com', 
  'kotaku.com', 'polygon.com', 'destructoid.com', 'rockpapershotgun.com', 'eurogamer.net', 'pcgamer.com', 
  'gematsu.com', 'siliconera.com', 'nintendolife.com', 'pushsquare.com', 'purexbox.com', 'shacknews.com', 
  'dualshockers.com', 'gamingbolt.com', 'gamerant.com', 'pockettactics.com', 'toucharcade.com', 
  'mmorpg.com', 'massivelyop.com', 'onrpg.com', 'mmobomb.com', 'mmohuts.com', 'rpgwatch.com', 
  'rpgcodex.net', 'gamedev.net', 'polycount.com', 'zbrushcentral.com', 'artstation.com', 'sketchfab.com', 
  'behance.net', 'deviantart.com', 'furaffinity.net', 'inkbunny.net', 'pixiv.net', 'patreon.com', 
  'subscribestar.com', 'gumroad.com', 'onlyfans.com', 'fansly.com', 'chaturbate.com', 'cam4.com', 
  'bongacams.com', 'stripchat.com', 'livejasmin.com', 'picarto.tv', 'smashcast.tv', 'mixer.com', 
  'theta.tv', 'vaughn.live', 'instasync.com', 'cytube.org', 'watch2gether.com', 'rave.io', 
  'discord.gg', 'guilded.gg', 'revolt.chat', 'chitchat.gg', 'mumble.info', 'teamspeak.com', 'ventrilo.com'
];
